### ISSUE TITLE
Not able to install plugin. 

### ISSUE THREAD

**Issue by AbhishekKataria** [DavidWittman/packer-post-processor-tarball#5]
Hi David, 
I am trying to get this plugin. But I am getting this error while installing it.
```
~/go$ go get github.com/DavidWittman/packer-post-processor-tarball
# github.com/DavidWittman/packer-post-processor-tarball/tarball
src/github.com/DavidWittman/packer-post-processor-tarball/tarball/post-processor.go:57: cannot use &p.config.ctx (type *"github.com/mitchellh/packer/template/interpolate".Context) as type *"github.com/hashicorp/packer/template/interpolate".Context in field value
src/github.com/DavidWittman/packer-post-processor-tarball/tarball/post-processor.go:60: cannot use "github.com/mitchellh/packer/template/interpolate".RenderFilter literal (type *"github.com/mitchellh/packer/template/interpolate".RenderFilter) as type *"github.com/hashicorp/packer/template/interpolate".RenderFilter in field value
```

I have my GOPATH set in the directory I am running from. Can you please let me know if I am doing anything wrong here. 

Thank you.

**Comment by tristanbettany** [comment]
I too have the same problem. It would be nice to know if a fix is possible. @AbhishekKataria Did you find an alternative solution to processing packer builds like this? I'm trying to make an OpenVZ compatible image using packer.

**Comment by DavidWittman** [comment]
@tristanbettany @AbhishekKataria This is happening because I was referencing the old Packer repository under mitchellh's account. Updating the imports to use hashicorp/packer seems to have fixed these issues. I know it's been a while, but let me know if you're still having any problems!
